spring.application.name=MS-INVENTARIO
server.port=8090

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://mysql_servidor_inventario:3306/inventario_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del microservicio Producto
producto.service.url=${PRODUCTO_SERVICE_URL:http://34.231.120.127:8084}

# Timeouts Feign
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Habilitar SpringDoc y Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Eureka
eureka.client.service-url.defaultZone=http://100.52.12.161:8761/eureka/
eureka.instance.prefer-ip-address=true

eureka.instance.hostname=100.52.12.161
eureka.instance.ip-address=100.52.12.161
eureka.instance.instance-id=${spring.application.name}:${server.port}
